FROM @scaffold.dockerphpfpm.docker.phpfpm.image@

RUN apk update && apk add apache-ant

COPY .@scaffold.dockerphpfpm.docker.phpfpm.srcdir@ @scaffold.dockerphpfpm.docker.phpfpm.destdir@
WORKDIR @scaffold.dockerphpfpm.docker.phpfpm.destdir@

RUN ant install configure build

ENV PATH="~/.composer/vendor/bin:./vendor/bin:${PATH}"